tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'thoughtbot/formulae'

brew 'ack'
brew 'age'
brew 'age-plugin-yubikey'
brew 'bash-completion'
brew 'duti'
brew 'git'
brew 'gh'
brew 'gnupg'
brew 'go'
brew 'golangci-lint'
brew 'grpcurl'
brew 'gum'
brew 'hadolint'
brew 'httpie'
brew 'jq'
brew 'libfido2'
brew 'mas'
brew 'nano'
brew 'openssh'
brew 'pyenv'
brew 'rcm'
brew 'shellcheck'
brew 'sops'
brew 'terraform'
brew 'tree'
brew 'ykman'
brew 'yq'

cask 'bloomrpc'
cask 'docker'
cask 'font-fira-code-nerd-font'
cask 'font-mononoki-nerd-font'
cask 'google-cloud-sdk'
cask '1password'
cask '1password-cli'
cask 'ngrok'
cask 'postico'
cask 'qlmarkdown'
cask 'spotify'
cask 'visual-studio-code'
# cask 'zoom'

mas "BetterJSON",           id: 1511935951
mas "1Password for Safari", id: 1569813296
mas "Sequel Ace",           id: 1518036000
# mas "Slack",                id: 803453959
