#!/usr/bin/env bash
# shellcheck source=/dev/null

[[ -f ~/.aliases ]] && source ~/.aliases
[[ -f ~/.secrets ]] && source ~/.secrets

# `brew shellenv` outputs the following:
# export HOMEBREW_PREFIX="/opt/homebrew";
# export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
# export HOMEBREW_REPOSITORY="/opt/homebrew";
# export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
# export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
# export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export HOMEBREW_NO_ENV_HINTS="1"
fi

if command -v code &>/dev/null; then
    export EDITOR="code --wait"
elif command -v nano &>/dev/null; then
    export EDITOR="nano"
fi

if [[ "${APP_ENV:-}" != "" ]]; then
    # "user@host(env):dir $ "
    export PS1="\[\033[01;32m\]\u@\h(\$APP_ENV)\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \$ "
else
    # "[user@host:dir] $ "
    export PS1="[\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]] \$ "
fi
export TERM=xterm-256color
export CLICOLOR=1
export MANPAGER="/usr/bin/less -R --use-color -Dd+c -Du+y"
export RIPGREP_CONFIG_PATH="${HOME}/.ripgreprc"

if command -v dircolors &>/dev/null; then
    # Set LS_COLORS for `tree`
    eval "$(dircolors -b)"
fi

export GOPATH="$HOME/go"
if [[ -d /usr/local/go/bin ]]; then
    # Go install dir (Linux).
    export PATH="$PATH:/usr/local/go/bin"
fi
export PATH="$PATH:$HOME/bin:$GOPATH/bin"

if [[ -d /opt/homebrew/share/google-cloud-sdk/bin ]]; then
    export PATH="/opt/homebrew/share/google-cloud-sdk/bin:$PATH"
fi

if [[ "$(uname -s)" == "Darwin" ]]; then
    export BASH_SILENCE_DEPRECATION_WARNING=1

    export HISTIGNORE="history*:exit"
    export HISTSIZE=5000
    export HISTFILESIZE=5000
    export HISTCONTROL=ignoreboth:erasedups
    shopt -s histappend
    # Merge history when closing terminal windows
    # Via: https://unix.stackexchange.com/a/556267
    function historymerge {
        history -n
        history -w
        history -c
        history -r
    }
    trap historymerge EXIT
    PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
fi

# Completion
if [[ -f "/opt/homebrew/etc/bash_completion" ]]; then
    source "/opt/homebrew/etc/bash_completion"
fi
if [[ -f "/etc/bash_completion" ]]; then
    source "/etc/bash_completion"
fi

if [[ -x "/opt/homebrew/bin/pyenv" ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
fi

[[ -f ~/.bashrc.local ]] && source ~/.bashrc.local
