#!/usr/bin/env bash
# shellcheck source=/dev/null

[[ -f ~/.aliases ]] && source ~/.aliases

# `brew shellenv` outputs the following:
# export HOMEBREW_PREFIX="/opt/homebrew";
# export HOMEBREW_CELLAR="/opt/homebrew/Cellar";
# export HOMEBREW_REPOSITORY="/opt/homebrew";
# export PATH="/opt/homebrew/bin:/opt/homebrew/sbin${PATH+:$PATH}";
# export MANPATH="/opt/homebrew/share/man${MANPATH+:$MANPATH}:";
# export INFOPATH="/opt/homebrew/share/info:${INFOPATH:-}";
if [[ -f /opt/homebrew/bin/brew ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if command -v brew &>/dev/null; then
    export EDITOR="code --wait"
elif command -v nano &>/dev/null; then
    export EDITOR="nano"
fi

# Color prompt: "user@host(env):dir $ "
export PS1="\[\033[01;32m\]\u@\h(\$APP_ENV)\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \$ "
export TERM=xterm-256color
export CLICOLOR=1

if command -v dircolors &>/dev/null; then
    # Set LS_COLORS for `tree`
    eval "$(dircolors -b)"
fi

export BASH_SILENCE_DEPRECATION_WARNING=1

export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$HOME/bin:$PATH"

if [[ "$(uname -s)" == "Darwin" ]]; then
    export HISTIGNORE="history*:exit"
    export HISTSIZE=5000
    export HISTFILESIZE=5000
    export HISTCONTROL=ignoreboth:erasedups
    shopt -s histappend
    # Merge history when closing terminal windows
    # Via: https://unix.stackexchange.com/a/556267
    function historymerge {
        history -n
        history -w
        history -c
        history -r
    }
    trap historymerge EXIT
    PROMPT_COMMAND="history -a; $PROMPT_COMMAND"
fi

# Completion
if [[ -f "/opt/homebrew/etc/bash_completion" ]]; then
    source "/opt/homebrew/etc/bash_completion"
fi
if [[ -f "/etc/bash_completion" ]]; then
    source "/etc/bash_completion"
fi

if [[ -x "/opt/homebrew/bin/pyenv" ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"
    eval "$(pyenv init -)"
fi

[[ -f ~/.bashrc.local ]] && source ~/.bashrc.local
